/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AIShelfLifeV2 {
  product: {
    name: string | null;
    barcode: string | null;
    category: string | null;
  };
  shelf_life: {
    unopened_days: number | null;
    opened_days: number | null;
    storage_temp: "cold" | "room" | "warm" | "frozen" | "unknown";
    adjustment_factor: number | null;
  };
  status: {
    confidence: number;
    reason_codes: (
      | "SKU_exact_match"
      | "SKU_fuzzy_match"
      | "OCR_low"
      | "OCR_ok"
      | "temperature_high"
      | "temperature_normal"
      | "opened"
      | "unopened"
      | "from_db"
      | "from_llm"
      | "from_user"
    )[];
    safe_to_consume: boolean;
  };
  metadata: {
    last_updated: string;
    source: "LLM" | "DB" | "OCR" | "user_input";
  };
}
